name: graphrag_mobile
description: Advanced GraphRAG Mobile App

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  file_picker: ^6.1.1
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
